### ISSUE TITLE
add a product to my cart so I can collect my desired products in one place.

### ISSUE THREAD

**Issue by MerleESelf** [Neptune-GH/GraceShopper-project#25]
After clicking add to cart button on single poster view. 
-Going to grab id from req.params.id to know what poster we are updating. this will subtract from poster qty --
-Will also create new assoc. between cart and order table. 
-will send the user to cart page (can be change if needed) or re-render the page with qty. 
-thunks in redux that will make axios call to update db 
-reducer for cart details and all posters 
-express route to update db.

**Comment by gender-outlaw** [comment]
So far:
- completed subtract from poster.qty 
- re/render page with qty (this is. the easiest solution, and fine for now)
- now moving on to associations
